-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.chatsessions
(
    sessionid serial NOT NULL,
    userid integer NOT NULL,
    sessiontopic character varying(255) COLLATE pg_catalog."default",
    datecreated timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chatsessions_pkey PRIMARY KEY (sessionid)
);

CREATE TABLE IF NOT EXISTS public.messages
(
    messageid serial NOT NULL,
    sessionid integer NOT NULL,
    sender character varying(50) COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    reply_to integer,
    "timestamp" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    approved boolean DEFAULT false,
    approved_by integer,
    approved_at timestamp without time zone,
    message_type character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'text'::character varying,
    caption text COLLATE pg_catalog."default",
    CONSTRAINT messages_pkey PRIMARY KEY (messageid)
);

CREATE TABLE IF NOT EXISTS public.users
(
    userid serial NOT NULL,
    username character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(50) COLLATE pg_catalog."default" NOT NULL,
    datecreated timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (userid),
    CONSTRAINT users_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.chatsessions
    ADD CONSTRAINT chatsessions_userid_fkey FOREIGN KEY (userid)
    REFERENCES public.users (userid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.messages
    ADD CONSTRAINT messages_approved_by_fkey FOREIGN KEY (approved_by)
    REFERENCES public.users (userid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.messages
    ADD CONSTRAINT messages_reply_to_fkey FOREIGN KEY (reply_to)
    REFERENCES public.messages (messageid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.messages
    ADD CONSTRAINT messages_sessionid_fkey FOREIGN KEY (sessionid)
    REFERENCES public.chatsessions (sessionid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;